# Generated by Django 3.2.5 on 2022-04-17 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskTrackerApp', '0002_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Members',
        ),
        migrations.AddField(
            model_name='team',
            name='Members',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
