# Generated by Django 3.2.5 on 2022-04-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0004_auto_20220417_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Members',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
