# Generated by Django 3.2.5 on 2022-04-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0006_auto_20220417_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
        migrations.AddField(
            model_name='members',
            name='name',
            field=models.ManyToManyField(blank=True, to='taskTrackerApp.Team'),
        ),
    ]
