# Generated by Django 3.2.5 on 2022-04-17 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskTrackerApp', '0007_auto_20220417_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
