# Generated by Django 3.2.5 on 2022-04-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0011_auto_20220417_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='teamId',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='teammembers',
            old_name='team',
            new_name='team_name',
        ),
    ]
