# Generated by Django 3.2.5 on 2022-04-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0012_auto_20220417_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='availability',
            field=models.BooleanField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='userId',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='teamId',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
