# Generated by Django 3.2.5 on 2022-04-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0013_auto_20220417_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='team_name',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='members',
            name='availability',
        ),
        migrations.AddField(
            model_name='members',
            name='memberId',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='availability',
            field=models.BooleanField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamId',
            field=models.IntegerField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='team_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='taskTrackerApp.team', to_field='teamId'),
        ),
    ]
