# Generated by Django 3.2.5 on 2022-04-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0015_auto_20220417_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='memberId',
        ),
    ]
