# Generated by Django 3.2.5 on 2022-04-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0016_remove_members_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='member',
            field=models.CharField(max_length=30),
        ),
    ]
