# Generated by Django 3.2.5 on 2022-04-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0019_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamId',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
