# Generated by Django 3.2.5 on 2022-04-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0020_alter_team_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamId',
            field=models.IntegerField(max_length=30, null=True, unique=True),
        ),
    ]
