# Generated by Django 3.2.5 on 2022-04-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0021_auto_20220418_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskTrackerApp.members', to_field='availability'),
        ),
        migrations.AlterField(
            model_name='members',
            name='availability',
            field=models.BooleanField(max_length=10, null=True, unique=True),
        ),
    ]
