# Generated by Django 3.2.5 on 2022-04-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0022_auto_20220418_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='availability',
        ),
        migrations.AlterField(
            model_name='members',
            name='availability',
            field=models.BooleanField(max_length=10, null=True),
        ),
    ]
