# Generated by Django 3.2.5 on 2022-04-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0023_auto_20220418_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=30)),
                ('priority', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateField(blank=True, max_length=30)),
                ('end_date', models.DateField(blank=True, max_length=30)),
                ('team_member', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
