# Generated by Django 3.2.5 on 2022-04-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0024_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='availability',
            field=models.BooleanField(max_length=10, null=True, unique=True),
        ),
    ]
