# Generated by Django 3.2.5 on 2022-04-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0027_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
