# Generated by Django 3.2.5 on 2022-04-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0028_auto_20220418_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
