# Generated by Django 3.2.5 on 2022-04-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0031_auto_20220418_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
    ]
