# Generated by Django 3.2.5 on 2022-04-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0032_remove_task_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
