# Generated by Django 3.2.5 on 2022-04-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0033_members_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamLeader',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
