# Generated by Django 3.2.5 on 2022-04-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskTrackerApp', '0035_remove_team_teamleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_on',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
